name: Generate Dart Documentation

on:
  push:
    branches:
      - main  # Spécifiez la branche sur laquelle vous voulez déclencher l'action

permissions:
  contents: write  # Assurez-vous que le token a les permissions nécessaires

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.3'

    - name: Install dependencies
      run: flutter pub get

    - name: Install dartdoc
      run: flutter pub global activate dartdoc

    - name: Add Pub Cache to PATH
      run: echo "${HOME}/.pub-cache/bin" >> $GITHUB_PATH

    - name: Generate documentation
      run: dartdoc

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/api  # Le répertoire de sortie par défaut de dartdoc est "doc/api"
        destination_dir: documentation  # Optionnel : nom du répertoire sur GitHub Pages
