name: Generate Dart Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.3'

    - name: Install dependencies
      run: flutter pub get

    - name: Install dartdoc
      run: flutter pub global activate dartdoc

    - name: Add Pub Cache to PATH
      run: echo "${HOME}/.pub-cache/bin" >> $GITHUB_PATH

    - name: Generate documentation
      run: dartdoc

    - name: Move documentation to docs folder
      run: |
        mkdir -p docs
        mv documentation/* docs/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Le répertoire où se situe la doc Flutter
        publish_dir: ./docs  # Déploie le contenu dans le répertoire 'docs'