name: Generate Dart Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.3'

    - name: Install dependencies
      run: flutter pub get

    - name: Install dartdoc
      run: flutter pub global activate dartdoc

    - name: Add Pub Cache to PATH
      run: echo "${HOME}/.pub-cache/bin" >> $GITHUB_PATH

    - name: Generate documentation
      run: dartdoc

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/api  # Le répertoire où se situe la doc Flutter
        destination_dir: docs  # Nom du répertoire sur GitHub Pages sur la branche gh-pages
